---
authors:
  - Nilashish Chakraborty (@NilashishC)
dependencies:
  ansible.netcommon: ">=6.0.0"
  ansible.utils: ">=3.0.0"
license_file: LICENSE
tags: [cisco, networking, eda]
namespace: network
name: telemetry
description: An Ansible Collection for managing telemetry configuration on network devices and integrate with Event-Driven Ansible (EDA).
readme: README.md
repository: https://github.com/redhat-cop/network.telemetry
issues: https://github.com/redhat-cop/network.telemetry/issues
version: "3.0.0"
