---
- name: Detect target host distribution
  ansible.builtin.set_fact:
    distro: "{{ 'rhel' if (ansible_distribution == 'RedHat') else (ansible_distribution | lower) }}"

- name: Check if distro is supported
  ansible.builtin.assert:
    that: distro in supported_distros
    fail_msg: "{{ distro }} is not supported."

- name: Start action deploy_collector
  ansible.builtin.debug:
    msg: "### Starting deploy_collector action ###"

- name: Install docker
  ansible.builtin.include_tasks: includes/docker.yaml

- name: Start docker containers
  ansible.builtin.include_tasks: includes/docker_compose.yaml
