---
- name: Load specified checks
  ansible.builtin.set_fact:
    checks: "{{ action['vars']['checks'] | d([]) }}"
    failed_checks: []
- name: Include tasks
  ansible.builtin.include_tasks: ./health_checks/{{ ansible_network_os.split('.')[-1] }}/{{ check.name }}.yaml
  loop: "{{ checks }}"
  loop_control:
    label: "{{ check.name }}"
    loop_var: check

- name: Validate health check results
  ansible.builtin.set_fact:
    failed_checks: "{{ failed_checks + [check.name] }}"
  when: not _{{ check.name }}
  loop: "{{ checks }}"
  loop_control:
    loop_var: check
    label: "{{ check.name }}"

- name: Show all checks that failed
  ansible.builtin.debug:
    var: failed_checks
  failed_when: failed_checks
