---
# tasks file for run
- name: Include tasks
  ansible.builtin.include_tasks: includes/{{ operation.name }}.yaml
  loop: "{{ operations }}"
  loop_control:
    loop_var: operation
    label: "{{ operation.name }}"
